In [1]:
import numpy as np
m=np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [2]:
m[1, 0]

5

In [4]:
m[1,:]

matrix([[5, 6, 7, 8]])

In [5]:
m[:,2]

matrix([[3],
        [7],
        [5]])

In [6]:
m[1, 2 :]

matrix([[7, 8]])

In [7]:
m[0:2,1]

matrix([[2],
        [6]])

In [8]:
m[0:2, 1:3]

matrix([[2, 3],
        [6, 7]])

In [9]:
cols=[0,1,3]
m[:, cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

In [10]:
m=np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [11]:
type(m)

numpy.matrix

In [12]:
m=np.array(m)
type(m)

numpy.ndarray

In [13]:
m.shape

(3, 4)

In [14]:
m.max()

9

In [15]:
m.max(axis=1)

array([4, 8, 9])

In [16]:
m=np.matrix(m)

In [17]:
m.max(axis=1)

matrix([[4],
        [8],
        [9]])

In [18]:
m.max(axis=0)

matrix([[9, 6, 7, 8]])

In [19]:
m.mean()

4.833333333333333

In [20]:
m.mean(axis=1)

matrix([[2.5],
        [6.5],
        [5.5]])

In [21]:
m.sum()
m.sum(axis=0)

matrix([[15,  9, 15, 19]])

In [22]:
nums=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters=np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

In [23]:
a=True

In [24]:
b=5>7

In [25]:
print(b)

False


In [26]:
less_then_5=nums<5

In [27]:
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [28]:
pos_a=letters=='a'

In [29]:
pos_a

array([ True, False, False, False,  True, False, False])

In [30]:
nums[less_then_5]

array([1, 2, 3, 4])

In [31]:
m=np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')

In [32]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [33]:
mod_m=np.logical_and(m>=3,m<=7)

In [34]:
mod_m

matrix([[False, False,  True,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [35]:
m[mod_m]

matrix([[3, 4, 5, 6, 7, 5, 7]])

In [36]:
nums=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [37]:
nums[nums<5]

array([1, 2, 3, 4])

In [38]:
nums[nums<5]=10

In [39]:
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [40]:
m[m>7]=25

In [41]:
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]


In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(5,12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [44]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [45]:
a=[[1,2],[3,4]]

In [46]:
np.matrix(a)

matrix([[1, 2],
        [3, 4]])

In [47]:
b=np.array([[5,6],[7,8]])

In [48]:
np.matrix(b)

matrix([[5, 6],
        [7, 8]])

In [49]:
np.matrix('[1,2;3,4]')

matrix([[1, 2],
        [3, 4]])

In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.ravel(A, order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.ravel(A, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [57]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [58]:
np.where(a%2==0,a*10,a/10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])

In [59]:
a=np.random.rand(10)

In [60]:
a

array([0.84084703, 0.60204262, 0.85939559, 0.16051418, 0.22293724,
       0.47226327, 0.09990886, 0.67620995, 0.21949436, 0.0256525 ])

In [61]:
np.where(a>0.5, True, False)

array([ True,  True,  True, False, False, False, False,  True, False,
       False])

In [62]:
np.where(a>0.5,1,-1)

array([ 1,  1,  1, -1, -1, -1, -1,  1, -1, -1])

In [63]:
x=np.linspace(0,1,5)

In [64]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [65]:
y=np.linspace(0,2,5)

In [66]:
y

array([0. , 0.5, 1. , 1.5, 2. ])

In [1]:
np.ravel(A)

NameError: name 'np' is not defined

In [2]:
np.ravel(A, order='C')

NameError: name 'np' is not defined

In [4]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

NameError: name 'np' is not defined

In [5]:
np.where

NameError: name 'np' is not defined

In [6]:
import numpy as np

In [7]:
np.ravel(A)

NameError: name 'A' is not defined

In [8]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.where(a%2==0, a*10, a/10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])

In [10]:
a=np.random.rand(10)

In [11]:
a

array([0.74045847, 0.38317699, 0.54463184, 0.00734538, 0.57716995,
       0.0384941 , 0.78457164, 0.67723515, 0.23376135, 0.36237431])

In [12]:
np.where(a>0.5, True, False)

array([ True, False,  True, False,  True, False,  True,  True, False,
       False])

In [13]:
np.where(a>0.5, 1, -1)

array([ 1, -1,  1, -1,  1, -1,  1,  1, -1, -1])

In [14]:
import matplotlib.pyplot as plt

In [15]:
%matplotlib inline

In [16]:
plt.plot(xg, yg, color="r", marker="*", linestyle="none")

NameError: name 'xg' is not defined

In [17]:
x=np.linspace(0,1,5)

In [18]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
y=np.linspace(0,2,5)

In [20]:
y

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
xg, yg =np.meshgrid(x, y)

In [22]:
xg

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [23]:
yg

array([[0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. ]])

In [24]:
import matplotlib.pyplot as plt

In [25]:
%matplotlib inline

In [26]:
plt.plot(xg, yg, color="r", marker="*",  linestyle="none")

SyntaxError: invalid non-printable character U+00A0 (2126499332.py, line 1)